### ISSUE TITLE
The Transition class uses Object for labels instead of a generic parameter

### ISSUE THREAD

**Issue by andrewdbate** [abailly/jautomata#4]
Currently, labels in rationals.Transition has type Object. If a generic type for labels were introduced for Transition, then casting would be avoided in calling code.

If you agree to this change, then I would be happy to implement it and send you a pull request.

**Comment by abailly** [comment]
Go ahead! That's something I always wanted to do... And BTW, this should also be the case for state I think :-) 

I would be happy to merge a PR

**Comment by andrewdbate** [comment]
This has been fixed by PR #7.
